apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-cd-workflow-role
  namespace: demo # Make sure this matches your namespace
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
