apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-namespace-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: math
            repoURL: https://github.com/naveenpatilcbit/devops_argo_cd/
            path: apps/mysecondapp
          - namespace: science
            repoURL: https://github.com/naveenpatilcbit/devops_argo_cd/
            path: apps/mythirdapp
  template:
    metadata:
      name: "{{namespace}}-app"
    spec:
      project: your-project
      source:
        repoURL: "{{repoURL}}"
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
