apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-helm-chart2
  namespace: argocd # Ensure this matches the namespace where Argo CD is installed
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/naveenpatilcbit/devops_argo_cd/"
    targetRevision: "main"
    path: "apps/Helm/simple-chart"
    helm:
      releaseName: hello-world
      valueFiles:
        - "values.yaml"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
