apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo-app
    version: blue # Initially pointing to the Blue version
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
