apiVersion: v2
name: myapp
version: 0.1.0

dependencies:
  - name: redis
    version: "20.6.1"
    repository: "https://charts.bitnami.com/bitnami"
  - name: mysql
    version: "12.2.1"
    repository: "https://charts.bitnami.com/bitnami"