apiVersion: v1
kind: Service
metadata:
  name: stable-service
  namespace: demo
spec:
  selector:
    app: canary-app # stable pods must have this label
  ports:
    - name: http
      port: 8083
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: canary-service
  namespace: demo
spec:
  selector:
    app: canary-app # canary pods will temporarily share these labels
  ports:
    - name: http
      port: 8083
      targetPort: 8080
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-rollout
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:22.0.0 # Your new version
          ports:
            - containerPort: 80
  strategy:
    canary:
      canaryService: canary-service
      stableService: stable-service
      steps:
        - setWeight: 25 # 25% traffic to the new version
        - pause:
            duration: 60 # Pause for 60 seconds, watch metrics/logs
        - setWeight: 50 # If still good, shift 50% traffic
        - pause:
            duration: 60
        - setWeight: 100 # Shift all traffic to new version if no issues
