apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-cron
  namespace: demo # Ensure this matches where Argo Workflows is installed
spec:
  schedule: "* * * * *" # Runs every minute
  concurrencyPolicy: "Allow" # Allows overlapping runs
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  workflowSpec:
    entrypoint: hello
    templates:
      - name: hello
        container:
          image: alpine:latest
          command: [echo]
          args: ["Hello from Cron Workflow!"]
